fix code bug
containerd/nri pull request #39
Opened 2023-05-17 04:39 UTC by ZP-AlwaysWin

the keys in code's bits map is lowercase
```
bits := map[string]Event{
		"runpodsandbox":       Event_RUN_POD_SANDBOX,
		"stoppodsandbox":      Event_STOP_POD_SANDBOX,
		"removepodsandbox":    Event_REMOVE_POD_SANDBOX,
		"createcontainer":     Event_CREATE_CONTAINER,
		"postcreatecontainer": Event_POST_CREATE_CONTAINER,
		"startcontainer":      Event_START_CONTAINER,
		"poststartcontainer":  Event_POST_START_CONTAINER,
		"updatecontainer":     Event_UPDATE_CONTAINER,
		"postupdatecontainer": Event_POST_UPDATE_CONTAINER,
		"stopcontainer":       Event_STOP_CONTAINER,
		"removecontainer":     Event_REMOVE_CONTAINER,
	}
```

so should fix if strings.Contains(name, "Pod") => if strings.Contains(name, "pod")

2023-05-17 05:11 UTC, ZP-AlwaysWin commented
/assign @fuweid
PTAL

2023-05-17 21:26 UTC, klihub requested changes
Thanks !

The fix itself is very valid, but could I ask you to rewrite the commit message to something a bit more descriptive. Maybe something like this:

"""
Fix `ParseEventMask` to produce proper masks for 'pod' and 'container' shorthand event notations.
"""

2023-05-18 02:04 UTC, ZP-AlwaysWin commented
> 

@klihub Thanks ! Modified PTAL

2023-05-18 06:03 UTC, Iceber approved these changes

2023-05-18 06:52 UTC, klihub approved these changes

2023-05-18 11:54 UTC, ZP-AlwaysWin commented
/assign @samuelkarp
PTAL

2023-05-18 19:11 UTC, klihub approved these changes

2023-05-19 01:54 UTC, Iceber approved these changes

2023-05-23 21:09 UTC, mikebrow approved these changes
LGTM

2023-05-23 21:10 UTC, merged

2023-11-01 18:28 UTC, dmcgowan commented
@ZP-AlwaysWin Do you want zhangpeng as name for change log?

2024-02-22 04:21 UTC, ZP-AlwaysWin commented
> @ZP-AlwaysWin Do you want zhangpeng as name for change log?

ok